// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(CreditoContext))]
    [Migration("20201111014613_InicialCreate")]
    partial class InicialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidad.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreditoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorAbono")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("AbonoId");

                    b.HasIndex("CreditoId");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("Entidad.Credito", b =>
                {
                    b.Property<int>("CreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorCredito")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("CreditoId");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("Entidad.Empresa", b =>
                {
                    b.Property<string>("EmpresaId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CantidadTrabajadores")
                        .HasColumnType("int");

                    b.Property<int?>("CreditoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ValorActivos")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("EmpresaId");

                    b.HasIndex("CreditoId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Entidad.Abono", b =>
                {
                    b.HasOne("Entidad.Credito", null)
                        .WithMany()
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entidad.Empresa", b =>
                {
                    b.HasOne("Entidad.Credito", "Credito")
                        .WithMany()
                        .HasForeignKey("CreditoId");
                });
#pragma warning restore 612, 618
        }
    }
}
